name: Deploy to ICP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install DFX
        run: |
          sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
          echo 'export PATH="$HOME/bin:$PATH"' >> $GITHUB_ENV

      - name: Decode and write identity.pem
        run: |
          mkdir -p ~/.config/dfx/identity/deploy
          echo "${{ secrets.DFX_IDENTITY_B64 }}" | base64 --decode > ~/.config/dfx/identity/deploy/identity.pem

      - name: Deploy to IC
        env:
          DFX_IDENTITY: deploy
        run: |
          dfx identity use deploy
          dfx deploy