name: Deploy to ICP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install DFX
        run: |
          curl -o dfx-install.sh https://internetcomputer.org/install.sh
            chmod +x dfx-install.sh
            DFX_VERSION=0.27.0 ./dfx-install.sh --yes
            echo "$HOME/.local/share/dfx/bin" >> $GITHUB_PATH

      - name: Decode and write identity.pem
        run: |
          mkdir -p ~/.config/dfx/identity/deploy
          echo "${{ secrets.DFX_IDENTITY_B64 }}" | base64 --decode > ~/.config/dfx/identity/deploy/identity.pem

      - name: Deploy to IC
        env:
          DFX_IDENTITY: deploy
        run: |
          dfx identity use deploy
          dfx deploy