name: Deploy to ICP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dfx
        run: |
          DFX_VERSION=0.27.0
          curl -L -o dfx "https://github.com/dfinity/sdk/releases/download/${DFX_VERSION}/dfx-${DFX_VERSION}-x86_64-linux.tar.gz"
          tar -xzf dfx -O > dfx-bin
          chmod +x dfx-bin
          mkdir -p ~/.local/share/dfx/bin
          mv dfx-bin ~/.local/share/dfx/bin/dfx
          echo "$HOME/.local/share/dfx/bin" >> $GITHUB_PATH
      
      - name: Start Local Replica
        run: |
          dfx start --background
          sleep 5  # wait for replica to be ready

      - name: Deploy to Local Replica
        run: |
          dfx identity use default
          dfx deploy