name: Deploy to ICP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install DFX
        run: |
          DFX_VERSION=0.27.0
          curl -L -o dfx.tar.gz "https://github.com/dfinity/sdk/releases/download/${DFX_VERSION}/dfx-${DFX_VERSION}-x86_64-linux.tar.gz"
          mkdir dfx-install
          tar -xzf dfx.tar.gz -C dfx-install
          ./dfx-install/dfx/install.sh --path "$HOME/.local/share/dfx"
          echo "$HOME/.local/share/dfx/bin" >> $GITHUB_PATH
      

      - name: Decode and write identity.pem
        run: |
          mkdir -p ~/.config/dfx/identity/deploy
          echo "${{ secrets.DFX_IDENTITY_B64 }}" | base64 --decode > ~/.config/dfx/identity/deploy/identity.pem

      - name: Deploy to IC
        env:
          DFX_IDENTITY: deploy
        run: |
          dfx identity use deploy
          dfx deploy